#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SQLiteApp.Resource", IsApplication=true)]

namespace SQLiteApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addnewbutton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int checkbox = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int CheckboxChecked = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int CheckboxUnchecked = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Delete = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int DeleteButton = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Edit = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int EditButton = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int PlusSign = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070026
			public const int addNew = 2131165222;
			
			// aapt resource value: 0x7f07000c
			public const int addOrderButton = 2131165196;
			
			// aapt resource value: 0x7f07001a
			public const int addStore = 2131165210;
			
			// aapt resource value: 0x7f07001d
			public const int address = 2131165213;
			
			// aapt resource value: 0x7f070014
			public const int address1 = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int address2 = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int city = 2131165206;
			
			// aapt resource value: 0x7f07000b
			public const int contactName = 2131165195;
			
			// aapt resource value: 0x7f07001c
			public const int cost = 2131165212;
			
			// aapt resource value: 0x7f07000a
			public const int date = 2131165194;
			
			// aapt resource value: 0x7f070025
			public const int delete = 2131165221;
			
			// aapt resource value: 0x7f070024
			public const int edit = 2131165220;
			
			// aapt resource value: 0x7f070021
			public const int linearLayout = 2131165217;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout2 = 2131165185;
			
			// aapt resource value: 0x7f07000f
			public const int linearLayout3 = 2131165199;
			
			// aapt resource value: 0x7f070013
			public const int managerName = 2131165203;
			
			// aapt resource value: 0x7f07001b
			public const int orderID = 2131165211;
			
			// aapt resource value: 0x7f070004
			public const int orderList = 2131165188;
			
			// aapt resource value: 0x7f070019
			public const int phoneNum = 2131165209;
			
			// aapt resource value: 0x7f070020
			public const int relativeLayout1 = 2131165216;
			
			// aapt resource value: 0x7f070008
			public const int rushOrder = 2131165192;
			
			// aapt resource value: 0x7f070012
			public const int sequenceNum = 2131165202;
			
			// aapt resource value: 0x7f070017
			public const int state = 2131165207;
			
			// aapt resource value: 0x7f07000e
			public const int storeID = 2131165198;
			
			// aapt resource value: 0x7f070022
			public const int storeIdEditText = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int storeList = 2131165219;
			
			// aapt resource value: 0x7f07000d
			public const int storeName = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int storeNum = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int territoryNum = 2131165201;
			
			// aapt resource value: 0x7f070005
			public const int textView1 = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int textView2 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int textView3 = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int textView4 = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int totalCost = 2131165190;
			
			// aapt resource value: 0x7f07001f
			public const int totalExpenses = 2131165215;
			
			// aapt resource value: 0x7f070007
			public const int totalItems = 2131165191;
			
			// aapt resource value: 0x7f07001e
			public const int totalOrdersButton = 2131165214;
			
			// aapt resource value: 0x7f070018
			public const int zip = 2131165208;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AllOrders = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int NewOrder = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NewStore = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int OrderDetails = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int OrderSummaryItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int StoreDetails = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int StoreListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Stores = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int EditDeleteMenu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int PlusMenu = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int inputbox = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
