#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SQLiteApp.Resource", IsApplication=true)]

namespace SQLiteApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addnewbutton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int PlusSign = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060021
			public const int addNew = 2131099681;
			
			// aapt resource value: 0x7f060017
			public const int address = 2131099671;
			
			// aapt resource value: 0x7f060011
			public const int contactName = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int cost = 2131099667;
			
			// aapt resource value: 0x7f06000e
			public const int date = 2131099662;
			
			// aapt resource value: 0x7f060007
			public const int editText1 = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int editText2 = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int editText3 = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int editText4 = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int editText5 = 2131099659;
			
			// aapt resource value: 0x7f06001e
			public const int linearLayout = 2131099678;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout2 = 2131099649;
			
			// aapt resource value: 0x7f060019
			public const int managerName = 2131099673;
			
			// aapt resource value: 0x7f06000d
			public const int orderID = 2131099661;
			
			// aapt resource value: 0x7f060004
			public const int orderList = 2131099652;
			
			// aapt resource value: 0x7f06001a
			public const int phoneNum = 2131099674;
			
			// aapt resource value: 0x7f060005
			public const int relativeLayout1 = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int relativeLayout2 = 2131099656;
			
			// aapt resource value: 0x7f060012
			public const int rushOrder = 2131099666;
			
			// aapt resource value: 0x7f060016
			public const int sequenceNum = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int storeID = 2131099668;
			
			// aapt resource value: 0x7f06001f
			public const int storeIdEditText = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int storeList = 2131099680;
			
			// aapt resource value: 0x7f06001d
			public const int storeName = 2131099677;
			
			// aapt resource value: 0x7f060018
			public const int storeNum = 2131099672;
			
			// aapt resource value: 0x7f060015
			public const int territoryNum = 2131099669;
			
			// aapt resource value: 0x7f06000c
			public const int textView1 = 2131099660;
			
			// aapt resource value: 0x7f060002
			public const int textView2 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int textView3 = 2131099651;
			
			// aapt resource value: 0x7f060010
			public const int totalCost = 2131099664;
			
			// aapt resource value: 0x7f06001c
			public const int totalExpenses = 2131099676;
			
			// aapt resource value: 0x7f06000f
			public const int totalItems = 2131099663;
			
			// aapt resource value: 0x7f06001b
			public const int totalOrdersButton = 2131099675;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AllOrders = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int NewStore = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int OrderDetails = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int OrderSummaryItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int StoreDetails = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int StoreListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Stores = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int PlusMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
